version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://db:3306/typing_test_project?createDatabaseIfNotExist=true"
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Lolownage00!
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Lolownage00!
      MYSQL_DATABASE: typing_test_project
    ports:
      - "3308:3308"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
