spring:
  datasource:
    url: jdbc:mysql://localhost:3306/typing_test_project?createDatabaseIfNotExist=true
    username: root
    password: Lolownage00!
  jpa:
    hibernate:
      ddl-auto: create-drop
